### ISSUE TITLE
some interesting pattterns in your work

### ISSUE THREAD

**Issue by timm** [zsthampi/SE17-Group-N#12]
- low number of total commits
- the feb report mentions an ROR site, not screen snaps. not sure if that is real of "vaporware" at this point
- the data mining stuff is interesting but you realize you need data to mine data, right? and if you cant get exactly what you want right now then the game changes: 
       - can you design an environment that would collect the necessity data such that data mining would become useful at some time in the future?

looking forward to seeing what parts of this are running, at the demos after the break.

**Comment by zsthampi** [comment]
- low number of total commits [We believe its because we've been working separately on implementations, and have less conflict. We've been doing some development on local machines. We will push more often going forward] 
- ROR site [We did the demo on our local machine. Plan to deploy the site before user evaluation. ETA : Mar 20]
- Data Mining [We plan to add current students and incoming students for Fall 2017 to the Piazza forum to get data. Till then, the plan is to get user evaluation by direct interviews/questionnaires for this implementation.]

**Comment by zsthampi** [comment]
I missed to mention earlier that our text mining algorithm uses the data from the P2P implementation via Piazza. So, as we get more reviews on the courses from students, we are expecting the text mining algorithm to get more accurate. (Assuming there is enough data for all the courses)
